### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by ghost** [ydlover/mindustry_admin#13]
The game provides you with a uuid,
It is the way your admin status is kept on servers when changing name, The current definition of uuid is name-ip, Resulting in a loss of status when changing names. Is there a way to access the game-defined uuid of ours?

**Comment by ydlover** [comment]
Do you want to get UUID information about a user in the game? Or ask how to fix the client's UUID

**Comment by ghost** [comment]
Both i guess. But i cant do it lol.

**Comment by ydlover** [comment]
Unable to do so currently on the client side, UUID information is printed in the connection log of each user on the server side.

**Comment by ghost** [comment]
If you don't get what i mean, The game has its own uuid and you should use it is what i mean.

**Comment by ghost** [comment]
Oh

**Comment by ydlover** [comment]
If you're talking about mindustry_admin, it currently uses UUID authentication
