### ISSUE TITLE
管理员图标丢失

### ISSUE THREAD

**Issue by linglan512572354** [ydlover/mindustry_admin#14]
目前版本游戏中已经没有name host指令了
此外今天更新的v104版本中 admin指令的使用方法发生了变化
同时这个版本又更新了所有玩家的uid，导致全部管理配置丢失。
由于以上两个原因，导致插件中设置的管理员在游戏中是没有管理权限的。

最后就是， 目前插件的人数统计有问题， 尤其是在切换地图的时候。 人数多了或者少了的情况都有存在。 status指令返回的结果是正确的。

**Comment by ydlover** [comment]
1)请使用2.10.3版本解决管理员权限问题(待发布)
2)管理员失灵请停止服务器后自行将admin.json中的UUID全部修改为空字符串后启动服务器，让大家重新绑定
